/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import gsap from 'gsap'

export default function LemonJar({ visible, customScale = 1.0, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/products/lemon_honey_500g.glb')

  useLayoutEffect(() => {
    if (visible) {
      gsap.fromTo(group.current.scale,
        { x: 0, y: 0, z: 0 },
        { x: 1, y: 1, z: 1, duration: 1, ease: "elastic.out(1, 0.5)", delay: 0.2 }
      );
      gsap.fromTo(group.current.rotation,
        { y: Math.PI * 2 },
        { y: 0, duration: 1.5, ease: "power3.out", delay: 0.2 }
      );
    }
  }, [visible]);

  // Floating Animation
  useFrame((state) => {
    if (!group.current) return;
    const t = state.clock.getElapsedTime();
    group.current.position.y = Math.sin(t * 1) * 0.1; // Gentle float
  });

  if (!visible) return null;

  return (
    <group ref={group} {...props} dispose={null}>
      {/* 📏 Dynamic Scale from Parent */}
      <group position={[0, 0, 0]} scale={[customScale, customScale, customScale]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/products/lemon_honey_500g.glb')
