#!/bin/bash
# Script to add GSAP animations to all cell components

CELLS=("Lemon" "Carob" "Thyme" "Blueberry" "Daghmous" "Rose")

for cell in "${CELLS[@]}"; do
  FILE="src/components/models/${cell}Cell.jsx"
  
  # Create temp file with GSAP animations
  cat > "${FILE}.tmp" << 'TEMPLATE'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with GSAP animations for Honeyverse
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

TEMPLATE,

  # Add the component function with GSAP
  sed -n '/^export default function/,$p' "$FILE" | sed '1s/^export default function Model/export default function CELLNAME/' | sed 's/const { nodes/const group = useRef()\n  const { nodes/' >> "${FILE}.tmp"
  
  # Insert GSAP animation before return
  sed -i '/const group = useRef()/a\
\
  // GSAP entrance animation\
  useEffect(() => {\
    if (group.current) {\
      gsap.set(group.current.scale, { x: 0, y: 0, z: 0 });\
      gsap.set(group.current.position, { y: -5 });\
\
      gsap.to(group.current.scale, {\
        x: props.scale || 1,\
        y: props.scale || 1,\
        z: props.scale || 1,\
        duration: 1.5,\
        ease: '\''elastic.out(1, 0.5)'\'',\
        delay: 0.3\
      });\
\
      gsap.to(group.current.position, {\
        y: props.position?.[1] || 0,\
        duration: 1.2,\
        ease: '\''power2.out'\'',\
        delay: 0.3\
      });\
    }\
  }, [props.scale, props.position]);' "${FILE}.tmp"
  
  # Replace group tag
  sed -i 's/<group {...props}/<group ref={group} {...props}/' "${FILE}.tmp"
  
  # Replace CELLNAME with actual cell name
  sed -i "s/CELLNAME/${cell}Cell/g" "${FILE}.tmp"
  
  # Move temp file to original
  mv "${FILE}.tmp" "$FILE"
  
  echo "✅ Added GSAP to ${cell}Cell.jsx"
done

echo "🎉 All cells updated with GSAP animations!"
