/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Torus: THREE.Mesh
    Torus001: THREE.Mesh
    Torus002: THREE.Mesh
    Torus003: THREE.Mesh
    Sphere: THREE.Mesh
    Torus005: THREE.Mesh
    Torus006: THREE.Mesh
    Torus007: THREE.Mesh
    Sphere001: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/beehive.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials['Material.003']}
        position={[0.02, -0.02, 0.06]}
        scale={[0.85, 0.84, 0.94]}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
        position={[0.02, 0.37, 0.06]}
        scale={[0.77, 0.88, 0.85]}
      />
      <mesh
        geometry={nodes.Torus002.geometry}
        material={nodes.Torus002.material}
        position={[0.01, 0.7, 0.06]}
        scale={[0.59, 0.88, 0.65]}
      />
      <mesh
        geometry={nodes.Torus003.geometry}
        material={materials['Material.005']}
        position={[0.01, 1.03, 0.06]}
        scale={[0.48, 0.88, 0.52]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[0, 1.2, 0.06]}
        scale={[0.48, 0.25, 0.54]}
      />
      <mesh
        geometry={nodes.Torus005.geometry}
        material={nodes.Torus005.material}
        position={[0.01, -0.37, 0.06]}
        rotation={[-0.02, 0.16, 3.14]}
        scale={[0.77, 0.88, 0.84]}
      />
      <mesh
        geometry={nodes.Torus006.geometry}
        material={nodes.Torus006.material}
        position={[0.02, -0.7, 0.07]}
        rotation={[-0.02, 0.16, 3.14]}
        scale={[0.59, 0.88, 0.65]}
      />
      <mesh
        geometry={nodes.Torus007.geometry}
        material={nodes.Torus007.material}
        position={[0.03, -1.03, 0.08]}
        rotation={[-0.02, 0.16, 3.14]}
        scale={[0.48, 0.88, 0.51]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.03, -1.27, 0.08]}
        rotation={[-0.02, 0.16, 3.14]}
        scale={[0.49, 0.25, 0.54]}
      />
    </group>
  )
}

useGLTF.preload('/models/beehive.glb')
