/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/carob_cell.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.tripo_node_3537baae.geometry}
        material={materials.tripo_mat_3537baae}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/carob_cell.glb')
