/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified for HoneyVerse project
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Beehive(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('/models/beehive.glb');

    return (
        <group ref={group} {...props} dispose={null}>
            {/* Bottom sphere */}
            <mesh
                geometry={nodes.Sphere001.geometry}
                material={nodes.Sphere001.material}
                position={[0.03, -1.27, 0.08]}
                rotation={[-0.02, 0.16, 3.14]}
                scale={[0.49, 0.25, 0.54]}
            />

            {/* Bottom torus layers */}
            <mesh
                geometry={nodes.Torus007.geometry}
                material={nodes.Torus007.material}
                position={[0.03, -1.03, 0.08]}
                rotation={[-0.02, 0.16, 3.14]}
                scale={[0.48, 0.88, 0.51]}
            />
            <mesh
                geometry={nodes.Torus006.geometry}
                material={nodes.Torus006.material}
                position={[0.02, -0.7, 0.07]}
                rotation={[-0.02, 0.16, 3.14]}
                scale={[0.59, 0.88, 0.65]}
            />
            <mesh
                geometry={nodes.Torus005.geometry}
                material={nodes.Torus005.material}
                position={[0.01, -0.37, 0.06]}
                rotation={[-0.02, 0.16, 3.14]}
                scale={[0.77, 0.88, 0.84]}
            />

            {/* Middle torus (widest) */}
            <mesh
                geometry={nodes.Torus.geometry}
                material={materials['Material.003']}
                position={[0.02, -0.02, 0.06]}
                scale={[0.85, 0.84, 0.94]}
            />

            {/* Top torus layers */}
            <mesh
                geometry={nodes.Torus001.geometry}
                material={nodes.Torus001.material}
                position={[0.02, 0.37, 0.06]}
                scale={[0.77, 0.88, 0.85]}
            />
            <mesh
                geometry={nodes.Torus002.geometry}
                material={nodes.Torus002.material}
                position={[0.01, 0.7, 0.06]}
                scale={[0.59, 0.88, 0.65]}
            />
            <mesh
                geometry={nodes.Torus003.geometry}
                material={materials['Material.005']}
                position={[0.01, 1.03, 0.06]}
                scale={[0.48, 0.88, 0.52]}
            />

            {/* Top sphere */}
            <mesh
                geometry={nodes.Sphere.geometry}
                material={nodes.Sphere.material}
                position={[0, 1.2, 0.06]}
                scale={[0.48, 0.25, 0.54]}
            />
        </group>
    );
}

useGLTF.preload('/models/beehive.glb');
