/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

export default function BeeHoneyCell(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/bee_cell.glb')

  // GSAP entrance animation
  useEffect(() => {
    if (group.current) {
      gsap.set(group.current.scale, { x: 0, y: 0, z: 0 });
      gsap.set(group.current.position, { y: -5 });

      gsap.to(group.current.scale, {
        x: props.scale || 1,
        y: props.scale || 1,
        z: props.scale || 1,
        duration: 1.5,
        ease: 'elastic.out(1, 0.5)',
        delay: 0.3
      });

      gsap.to(group.current.position, {
        y: props.position?.[1] || 0,
        duration: 1.2,
        ease: 'power2.out',
        delay: 0.3
      });
    }
  }, [props.scale, props.position]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.tripo_node_3537baae.geometry}
        material={materials.tripo_mat_3537baae}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/bee_cell.glb')
