/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

export default function BlueberryCell(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/blueberry_cell.glb')

  useEffect(() => {
    if (group.current) {
      gsap.set(group.current.scale, { x: 0, y: 0, z: 0 });
      gsap.set(group.current.position, { y: -5 });
      gsap.to(group.current.scale, { x: props.scale || 1, y: props.scale || 1, z: props.scale || 1, duration: 1.5, ease: 'elastic.out(1, 0.5)', delay: 0.3 });
      gsap.to(group.current.position, { y: props.position?.[1] || 0, duration: 1.2, ease: 'power2.out', delay: 0.3 });
    }
  }, [props.scale, props.position]);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['tripo_node_d25015c9-98eb-477f-8d74-8bf4850dadfb'].geometry}
        material={materials['tripo_material_d25015c9-98eb-477f-8d74-8bf4850dadfb']}
        position={[-0.03, 0.11, 0]}
        rotation={[-2.68, 0.86, 2.92]}
        scale={[1, 1.03, 1]}
      />
      <mesh
        geometry={nodes.tripo_node_59b2f49f.geometry}
        material={materials.tripo_mat_59b2f49f}
        position={[0, 0.07, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/blueberry_cell.glb')
