/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with GSAP animations for Honeyverse
INLINE VERSION - GLB embedded as Data URI
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

// IMPORTANT: This file is VERY LARGE (~30MB) because the GLB model is embedded as Base64
// For production, it's recommended to use the external file version (CarobCell.jsx)
// This inline version is only useful if you need to bundle everything in a single file

const CAROB_GLB_DATA_URI = 'data:model/gltf-binary;base64,' + `
[BASE64_DATA_WILL_BE_HERE_BUT_ITS_TOO_LARGE_TO_INCLUDE_IN_THIS_EXAMPLE]
`

export default function CarobCellInline(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF(CAROB_GLB_DATA_URI)

    // GSAP entrance animation
    useEffect(() => {
        if (group.current) {
            // Start invisible and scaled down
            gsap.set(group.current.scale, { x: 0, y: 0, z: 0 });
            gsap.set(group.current.position, { y: -5 });

            // Animate in with bounce
            gsap.to(group.current.scale, {
                x: props.scale || 1,
                y: props.scale || 1,
                z: props.scale || 1,
                duration: 1.5,
                ease: 'elastic.out(1, 0.5)',
                delay: 0.3
            });

            gsap.to(group.current.position, {
                y: props.position?.[1] || 0,
                duration: 1.2,
                ease: 'power2.out',
                delay: 0.3
            });
        }
    }, [props.scale, props.position]);

    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                geometry={nodes.tripo_node_9a113449.geometry}
                material={materials.tripo_mat_9a113449}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

// No need for preload since the data is already embedded
