/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with GSAP animations for Honeyverse
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function DaghmousCell(props) {
  const { nodes, materials } = useGLTF('/models/daghmous_cell.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tripo_node_88ff9473.geometry}
        material={materials.tripo_mat_88ff9473}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/daghmous_cell.glb')
