/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function HoneyJar(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/honey_jar.glb')

    useFrame((state) => {
        if (group.current) {
            // Floating animation - ADD to base position instead of replacing it
            const baseY = props.position ? props.position[1] : 0;
            group.current.position.y = baseY + Math.sin(state.clock.elapsedTime * 0.5) * 0.1;
            // Slow rotation
            group.current.rotation.y += 0.005;
        }
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, 0, 0]}> {/* Reset position to center */}
                <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.002']} />
                <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.003']} />
                <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.004']} />
                <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.005']} />
            </group>
        </group>
    )
}

useGLTF.preload('/models/honey_jar.glb')
