/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with GSAP animations for Honeyverse
*/

import { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import gsap from 'gsap';

export default function LemonCell(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('/models/lemon_cell.glb');

    // GSAP entrance animation
    useEffect(() => {
        if (group.current) {
            // Start invisible and scaled down
            gsap.set(group.current.scale, { x: 0, y: 0, z: 0 });
            gsap.set(group.current.position, { y: -5 });

            // Animate in with bounce
            gsap.to(group.current.scale, {
                x: props.scale || 1,
                y: props.scale || 1,
                z: props.scale || 1,
                duration: 1.5,
                ease: 'elastic.out(1, 0.5)',
                delay: 0.3
            });

            gsap.to(group.current.position, {
                y: props.position?.[1] || 0,
                duration: 1.2,
                ease: 'power2.out',
                delay: 0.3
            });
        }
    }, [props.scale, props.position]);

    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                geometry={nodes.tripo_node_888b3cfa.geometry}
                material={materials.tripo_mat_888b3cfa}
                position={[1.06, 0, -0.57]}
                rotation={[-Math.PI / 2, 0, 0]}
                castShadow
                receiveShadow
            />
        </group>
    );
}

useGLTF.preload('/models/lemon_cell.glb');
