/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with GSAP animations for Honeyverse
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function RoseCell(props) {
  const { nodes, materials } = useGLTF('/models/rose_cell.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tripo_node_e08faa72.geometry}
        material={materials.tripo_mat_e08faa72}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/rose_cell.glb')
