/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with GSAP animations for Honeyverse
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function ThymeCell(props) {
  const { nodes, materials } = useGLTF('/models/thyme_cell.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tripo_node_3e8ac62a.geometry}
        material={materials.tripo_mat_3e8ac62a}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/thyme_cell.glb')
